apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedev
spec:
  template:
    spec:
      containers:
      - name: onedev
        resources:
          requests: 
            memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          requests: 
            memory: 500Mi
