apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedev
spec:
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
